seed: 1
use_cuda: False
sigma_final: 2
sigma_init: 2
gamma_final: 1
gamma_init: 1
plot_style: dark


# only for models with "nn-[one|inf]"
max_norm:
  - True
  # - False

# only for models with "nn-[one|inf]"
division:
  # - "scalar"
  - "vector"

# only for models with "nn-[one|inf]"
regularization:
  # - "project"
  - "direct"

model :
  # - "nn-inf-oc" # sigma of .2 hardcoded
  # - "nn-inf-small"
  # - "nn-inf-mon-vchi2" # monotonically decreasing in vchi2
  - "nn-inf"
  # - "nn-one"
  - "bdt"
  - "nn-regular"
  # - "lda"
  # - "qda"
  # - "gnb"

data_type:
  - "lhcb"
  # - "standalone"

features:
  # - ["minipchi2", "sumpt"]
  # - ["fdchi2", "sumpt"]
  - ["fdchi2", "sumpt", "vchi2", "minipchi2"]

signal_type:
  - "heavy-flavor"
  # - "beauty"
  # - "charm"

normalize:
  - False
  # - True

presel_conf:
  # - svPT : 2000 # [MeV]
  #   trkPT : 500 # [MeV]
  #   svchi2 : 10 # [unitless]
  # - svPT : 1000 # [MeV]
  #   trkPT : 500 # [MeV]
  #   svchi2 : 10 # [unitless]
  # - svPT : 1000 # [MeV]
  #   trkPT : 200 # [MeV]
  #   svchi2 : 20 # [unitless]
  #   ipcuttrain : 6 # ip cut in for training
  - svPT : 1000 # [MeV]
    trkPT : 200 # [MeV]
    svchi2 : 20 # [unitless]
    ipcuttrain : 10 # (effectively no cut)
