seed: 100
use_cuda: False
sigma_final: 10
sigma_init: 10
gamma_final: 1
gamma_init: .5
plot_style: None
# list all possible configurations (cartesian product of these)
nn_args:
 - sigma: [False, True]
 - division: ["scalar", "vector"]
 - regularization: ["project", "diffable"]

model :
  # - "nn-one"
  - "nn-regular"
  # - "nn-inf"
  # - "bdt"
  # - "lda"
  # - "qda"
  # - "gnb"
data_type :
  - "lhcb"
  # - "standalone"
features :
  - ["minipchi2", "sumpt"]
  # - ["fdchi2", "sumpt"]
  # - ["fdchi2", "sumpt", "vchi2", "minipchi2"]
signal_type :
  - "heavy-flavor"
  # - "beauty"
  # - "charm"
normalize :
  - False
  # - True
presel_conf :
  - svPT : 2000 # [MeV]
    trkPT : 500 # [MeV]
  # - svPT : 1000 # [MeV]
  #   trkPT : 500 # [MeV]
