seed: 100
use_cuda: False
sigma_final: 3
sigma_init: 1
# plot_style: None
# list all possible configurations (cartesian product of these)
model :
  - "sigma"
  - "sigma-safe"
  # - "regular"
  # - "bdt"
  # - "lda"
  # - "qda"
  # - "gnb"
data_type :
  - "lhcb"
  # - "standalone"
features :
  - ["minipchi2", "sumpt"]
  # - ["fdchi2", "sumpt"]
  # - ["fdchi2", "sumpt", "vchi2", "minipchi2"]
signal_type :
  - "heavy-flavor"
  # - "beauty"
  # - "charm"
normalize :
  - False
  # - True
presel_conf :
  - svPT : 2000 # [MeV]
    trkPT : 500 # [MeV]
  - svPT : 1000 # [MeV]
    trkPT : 500 # [MeV]
